spring:
  datasource:
    url: jdbc:postgresql://localhost:26257/roach_data?ssl=true&sslmode=disable
    username: maxroach
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto:  create
server:
  port: 8081