spring:
  datasource:
    url: jdbc:postgresql://localhost:26257/roach_data?ssl=true&sslmode=disable
    username: maxroach
  jpa:
    generate-ddl: true
    hibernate:
#      ddl-auto: update
      ddl-auto:  create
#  security:
#    user:
#      name: bob
#      password: pw
#      roles: USER
server:
  port: 8081
#springdoc:
#  api-docs:
#    path: /blog-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#    operations-sorter: method